---
name: github-playground
on:
  workflow_dispatch:
    inputs:
      command:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          cat /etc/os-release
          ${{ inputs.command }}
