---
name: github-playground
on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          cat /etc/os-release
          echo ${{ inputs.message }}}
